services:
  db:
    image: postgres:16-alpine

    ports:
      - 127.0.0.1:5432:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
